[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
logfile = /var/lib/odoo/odoo.log
log_level = info

; JSON-RPC / Web
xmlrpc = True
xmlrpc_port = 8069
longpolling_port = 8072

; Security
list_db = True
admin_passwd = gold_admin_2024

; Performance
workers = 2
max_cron_threads = 1
limit_time_cpu = 600
limit_time_real = 1200
